export { Home } from "./Home/Home.page";
export { Login } from "./Login/Login.page";
export { NotFound } from "./NotFound/NotFound.page";
export { Checkers } from "./Checkers/Checkers.page";
export { Actions } from "./Actions/Actions.page";
export { Questions } from "./Questions/Questions.page";
export { Announcements } from "./Announcements/Announcements.page";
export { Flows } from "./Flows/Flows.page";
export { DrawFlow } from "./Flows/DrawFlow/DrawFlow.page";
